development:
  adapter: postgresql
  database: rachelsblog_development
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  database: rachelsblog_production
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  database: rachelsblog_test
  pool: 5
  username:
  password:
